### ISSUE TITLE
Discussion: AWS ec2 cpu 사용률 증가 및 쓰로틀링 현상

### ISSUE THREAD

**Issue by Istiopaxx** [Jandy-SeoulTech/Jandy_Web_Back#100]
## 문제상황.
- 현재 서버 배포 구조는 ec2 인스턴스에 도커 컨테이너에서 api 서버와 mysql 디비를 두개 돌리고, nginx를 설치해 80, 443 포트 요청을 api 서버로 프록시 패스중입니다.
- mysql 디비는 개발시에 해당하는 포트에 ip 인바운드 룰을 모든 ip에 열고, 개발하지 않을 시에는 ip를 자기 자신만 허용하도록 설정하였습니다.
- 서버 배포이후 인스턴스 cpu 사용량이 급상승하여 ssh 접속은 물론 api서버가 트래픽을 처리하지 못하는 현상이 여러차례 발생하였습니다.
- 아래 cpu 사용량 사진에서 표시된 부분이 서버 다운입니다.
![캡처2](https://user-images.githubusercontent.com/38745815/136783027-53363ae2-653c-46b9-beb4-43de692a6bec.PNG)
- 제일 최근 서버 다운에서의 모니터링 지표를 보면
![캡처2](https://user-images.githubusercontent.com/38745815/136783424-7872c63a-e60b-4a66-a2a1-e86fdfa8c1be.PNG)
- 네트워크 입출력이 있긴 했으나 미미한 수준으로, 트래픽 과부하로 인한 서버 cpu 사용량 증가라고 생각되지 않습니다.
- 그 이전의 서버 다운 사례에서도 모니터링 지표 중 네트워크 입출력 지표는 큰 변화를 보이지 않았습니다.
![캡처2](https://user-images.githubusercontent.com/38745815/136784100-07cdcbbd-96e4-476b-a95e-39a96071c880.PNG)
- nginx access log인데, 서버 다운시점인 utc:08:58:00 이전에 그리 많은 요청이 오지 않았습니다. 즉 트래픽 문제는 아닙니다.
- 해당 시간의 docker 컨테이너 로그를 살펴볼건데, api서버의 로그는 nginx access log와 거의 같으므로 첨부하지 않겠습니다.
![캡처](https://user-images.githubusercontent.com/38745815/136784363-001cc73f-9a23-4829-914a-39b54d00aed3.PNG)
- 위 로그는 docker 컨테이너 중 mysql 디비 컨테이너 로그입니다. `mbind: Operation not permitted` 라는 에러메시지가 뜨다가 로그가 끊겼습니다. 이런 상태라면 해당 에러를 의심해볼만 합니다. 아래는 관련된 에러에 대한 검색 결과입니다.
- https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log
- https://data-engineer-tech.tistory.com/27
- 현재는 위 검색들에서 제시하는 대로 mysql 컨테이너를 --cap-add=sys_nice 옵션을 주어서 실행중입니다.

## 논의하고 싶은 것 

- 과연 위의 mbind 문제가 원인인지?
- 혹은 다른 것이 원인인지?
- 다른 것이 원인이라면 원인을 어떻게 찾아낼 것인지?
   + cpu 모니터링 지표 확인
   + 컨테이너 로그 고도화
   + 리소스 모니터링 및 이벤트 핸들러 등록?
- 동일하게 서버가 다운되는 현상이 또 발생하면, mysql 컨테이너 로그를 확인해보고, 별 이상이 없다면(현재는 옵션을 주어서 실행하여 mbind 에러가 발생하지 않을 것으로 예상) 다른 원인을 찾아봐야 합니다.

@InHyeok-J @iqeq1945 
의견 부탁드립니다.

**Comment by iqeq1945** [comment]
지금으로선, 무엇이 문제인지 따지기는 어려울 것 같습니다. 현재로선  mbind 문제라고 생각을 해야 할 것 같습니다.  언급하신 것 처럼 서버가 다운되는 현상이 또 발생하면, 로그를 분석을 해봐야 할 것 같습니다.

**Comment by Istiopaxx** [comment]
RDS로 디비 이전하여 이후 경과를 지켜보겠습니다. 현재 예상으로는 vcpu 1개, 메모리 1GB의 작은 컴퓨팅 리소스로 두개의 도커 컨테이너를 서비스하여 쉽게 리소스가 초과되는 것 같아, 디비를 이전하고 ec2인스턴스에선 api 서버 하나만 돌리려고 합니다. 이후에도 똑같이 서버다운 현상이 자주 일어난다면 다시 원인 조사하겠습니다.
