### ISSUE TITLE
Feat: GET /api/Chat/room/:roomId/answer 로직 변경

### ISSUE THREAD

**Issue by Istiopaxx** [Jandy-SeoulTech/Jandy_Web_Back#102]
## 개발사항

- 아카이빙 작성 시 채팅방 방장은 자신의 질문-답장쌍만 아카이빙하게 됩니다.
- 요청을 보낸 유저의 id값을 repository 함수에 전달하여 해당 유저의 질문-답장쌍만 가져와야 합니다.
### 레포지토리 함수 변경
- https://github.com/Jandy-SeoulTech/Jandy_Web_Back/blob/cc39a1b36a8bfb7d0dbbe022731a7331213ff9e2/src/repositories/ChatMessageRepository.js#L219-L251
- where 쿼리에서 sendUserId가 요청을 보낸 유저 id와 일치하는 걸로 필터링 필요

**Comment by InHyeok-J** [comment]
지난회의때 추가된거였는데 확인을 못했네요

**Comment by Istiopaxx** [comment]
## 작업사항 추가

- GET /api/Room/:channelId 에서 아무것도 없으면 빈배열 반환
- GET /api/Room/list
-
