### ISSUE TITLE
Discussion: 댓글 작성, 불러오기 API 내 type enum 명칭 변경

### ISSUE THREAD

**Issue by md2eoseo** [Jandy-SeoulTech/Jandy_Web_Back#103]
## 문제상황
아카이브 글이 추가되면서 댓글 작성, 불러오기 API에 type 쿼리가 생겼는데요,
댓글 작성에서는 [channel, archive] enum을 사용하고,
댓글 불러오기에서는 [post, archive] enum을 사용해서 명칭이 헷갈리는 것 같습니다.
channel을 post로 바꿔서 통일 시키면 이해하기 더 명확할 것 같은데 어떻게 생각하시나요?

<img width="497" alt="스크린샷 2021-10-12 13 43 32" src="https://user-images.githubusercontent.com/8054085/136893954-480440da-8faf-4515-b0a7-64d1b04771c1.png">
<img width="492" alt="스크린샷 2021-10-12 13 46 40" src="https://user-images.githubusercontent.com/8054085/136893957-3086ad59-b379-43b0-99f0-a866697cd56e.png">

**Comment by Istiopaxx** [comment]
아 문서가 잘못되어 있네요. 댓글 작성 api에서도 type 쿼리의 값이 enum[post, archive] 가 맞습니다. 
`POST /api/Comment/?type=channel&id=1`  로 요청하시면 아마 오류가 날거에요.
