### ISSUE TITLE
Bug: 채널 카테고리 스키마 변경 후 채널 카테고리 적용 불가

### ISSUE THREAD

**Issue by Istiopaxx** [Jandy-SeoulTech/Jandy_Web_Back#104]
**버그를 설명해주세요**
채널 카테고리 스키마 변경 이후 채널생성, 채널 수정이 불가합니다.

**재현방법**
버그를 재현하려면...
1. 현재 dev 브랜치 버전으로 서버를 킨다.(배포판도 현재 버전으로 되있음)
2. 클라이언트를 킨다.
3. 디버깅할 서버와 클라이언트를 클라이언트의 setUpProxy 파일에서 설정하여 연결한다.
4. 채널 만들기 기능을 사용할 시 서버에 찍히는 에러 로그 확인.

**맞는 동작**
채널 생성과 채널 정보 수정이 이루어져야함.

**스크린샷**
배포 서버 에러로그입니다.
![캡처3](https://user-images.githubusercontent.com/38745815/136945041-8b018e6a-1f73-4e69-9f13-2087af4b24f0.png)
```
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: An operation failed because it depends on one or more records that were required but not found. No 'Category' record (needed to inline connect on create for 'ChannelCategory' record) was found for a nested connect on one-to-one relation 'CategoryToChannelCategory'.
    at cb (/usr/app/node_modules/@prisma/client/runtime/index.js:34800:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'P2025',
  clientVersion: '2.28.0',
  meta: {
    cause: "No 'Category' record (needed to inline connect on create for 'ChannelCategory' record) was found for a nested connect on one-to-one relation 'CategoryToChannelCategory'."
  }
}
```

**추가적인 상황**
 @iqeq1945 클라 레포에 해당 api 수정 이슈 및 카테고리 이름<->코드 딕셔너리 전달하는 이슈 생성해서 클라 수정이 될 수 있도록 해주세요.

**Comment by Istiopaxx** [comment]
쿼리가 connect로 되어있는데 현재 디비에는 category 테이블에 아무 데이터가 없어서 발생하는 문제가 아닌가 생각되네요. 카테고리 이름<->코드 딕셔너리 완성하는대로 디비에 삽입하고 테스트해보면 좋을 것 같습니다.

**Comment by iqeq1945** [comment]
예상하신 것 처럼 디비에 카테고리데이터가 존재하지 않기 때문에 발생하는 일입니다. 오늘내로 딕셔너리 초안 작성 후, 논의로 올리도록하겠습니다.

**Comment by Istiopaxx** [comment]
#105
