### ISSUE TITLE
Feat : 카테고리 딕셔너리

### ISSUE THREAD

**Issue by iqeq1945** [Jandy-SeoulTech/Jandy_Web_Back#105]
## 개발사항

- 카테고리 딕셔너리
- 코드의 경우, 대문자로 이루어지도록 함.

### 딕셔너리
|name|code|
|------|------|
|미술 / 공예|ART|
|요리 / 조리|COOK|
|투자 / 부업|INVEST|
|외국어|LANGUAGE|
|디자인|DESIGN|
|패션 / 뷰티|BEAUTY|
|프로그래밍|PROGRAMMING|
|창업|STARTUP|
|음악|MUSIC|
|홈리빙 / 인테리어|INTERIOR|
|시험 / 자격증|EXAM|
|스포츠|SPORTS|
|연기 / 마술|ACT|
|펫 / 반려동물|PET|
|커리어|CAREER|
|건강|HEALTH|
|댄스|DANCE|
|여행|TRAVEL|
|학문|STUDY|
|인간관계|RELRATIONSHIP|
|라이프|LIFE|
|사진 / 영상|MEDIA|
|취미 생활|HOBBY|
|기타|ETC|

## 추가사항
- code의 글자 수를 맞추기에는 힘들 것 같아 이렇게 결정하였습니다.
- 글자수를 맞춰야한다면 이진수 코드를 이용하여 작성하는 것도 방법이 될 것 같습니다.

**Comment by Istiopaxx** [comment]
좋습니다~~ 글자수를 맞출 필요는 없어보입니다. 어차피 query url에선 구분자를 활용할 거니까 괜찮을 것 같아요. 
@md2eoseo @sjsjsj1246 이 데이터를 딕셔너리로 만들어서 클라쪽에 삽입하고, 카테고리를 활용하는 모든 곳에서 해당 딕셔너리를 사용해주세요.
@iqeq1945 문제없이 바로 디비에 데이터 삽입해주세요. 디비 접속은 마이그레이션한 rds쪽에 삽입해주시면 됩니다. 클라쪽도 동시에 수정 들어가겠습니다.

**Comment by Istiopaxx** [comment]
디비 데이터 삽입되었고 클라이언트도 맞춰서 수정되었으니 이슈는 닫겠습니다.
