### ISSUE TITLE
Bug: 룸 생성 시 Locale에 맞는 시간 설정 필요

### ISSUE THREAD

**Issue by sjsjsj1246** [Jandy-SeoulTech/Jandy_Web_Back#114]
**버그를 설명해주세요**
룸 예약 생성 시 시간이 AWS의 시간대로 설정되는 것 같음
Locale에 맞는 시간 설정 필요

**상황**
서버에서 저장하는 데이터 시간이 UTC가 아닌 것 같습니다.

**스크린샷**
https://github.com/Jandy-SeoulTech/Jandy_Web_Back/blob/49af0489f0f4f0af376bad96c907fa145688b4eb/src/services/RoomServices.js#L50-L70

```js
 const date = new Date(req.body.reservedTime); 
```
해당 부분에서 문제가 생기는 것 같습니다.

**추가적인 상황**
POST /api/Room 에서 UTC, GMT+0900둘다 보내봤는데 서버에는 -9시간돼서 저장되네요

**Comment by InHyeok-J** [comment]
```
const date = new Date(req.body.reservedTime); 
```
이부분은 그냥 문자열을 Date 객체로 바꿔주는 부분이 아닌지,, 문자열을 잘 주면 문제가 없을거같은데.. 이게 서버에 저장할때도 string을 받아와서 Date 객체로 바꿔서 저장을 시키는데 둘 중 어느부분이 문제인지 아니면 둘다 문제인지 파악하고 수정하겠습니다

**Comment by Istiopaxx** [comment]
https://github.com/Jandy-SeoulTech/Jandy_Web_Back/blob/dc3b36b2008606bfb558e08daf52ba8ff1ca3d12/src/repositories/ChannelRoomRepository.js#L58-L59
> 이부분은 그냥 문자열을 Date 객체로 바꿔주는 부분이 아닌지,, 문자열을 잘 주면 문제가 없을거같은데.. 이게 서버에 저장할때도 string을 받아와서 Date 객체로 바꿔서 저장을 시키는데 둘 중 어느부분이 문제인지 아니면 둘다 문제인지 파악하고 수정하겠습니다

저 이슈를 작성할땐 문제가 정확히 어디서 생기는지 몰라서 저렇게 작성되었는데, 실질적으로 문제가 생기는 부분은 이런 부분입니다. api 통신 시에 모든 시간 데이터는 뒤에 UTC시간을 뜻하는 Z 문자가 삽입되어서 주고받게 됩니다. 해당 부분은 mysql은 시간 데이터를 무조건 UTC로 저장하기 때문에(datetime은 타임존 정보를 저장안하고, timestamp는 타임존정보를 저장하는 차이는 있음) 쿼리를 날려서 받아오는 데이터도 UTC로 가져오는 것 때문으로 보입니다.
https://github.com/Jandy-SeoulTech/Jandy_Web_Back/blob/dc3b36b2008606bfb558e08daf52ba8ff1ca3d12/src/utils/dayUtils.js#L1-L3
해당 부분의 dbnow() 함수가 +9시간을 하여 api 통신에서 받은 UTC시간을 한국시간으로 맞춰서 mysql에 집어넣어도, mysql은 받은 시간 정보에 타임존 정보가 없으므로 (mysql상에서 확인해보니 DATETIME(3)으로 되어있음) UTC로 저장하게 됩니다. 쿼리 날려서 받은 데이터도 UTC로 받습니다. 


#### 현재상황.
1. 클라에서 서버에 시간 데이터를 보낼때는 "Fri, 15 Oct 2021 07:30:00 GMT" 이런식으로 갑니다. 
2. 클라에서 서버의 시간데이터를 받을때는 UTC string으로 받습니다. 근데 받은 데이터는 끝에 Z가 붙어있지만 한국시간 기준으로 맞춰져있습니다.(서버에서 +9 해줫음) 그럼 출력할때에는 한국기준으로 바꾸지 말고 그대로 써야합니다.

#### 해결법.
1. 클라이언트에서 데이터를 보낼때/받을때(즉 api 통신간)에서는 무조건 UTC, 서버에 저장하는 시간도 UTC, 클라에서 데이터를 입력 받을때와 출력할때엔 해당 클라이언트에 맞는 로케일로 입출력하는 걸로 통일하는 방안.
2. 현재 로직대로 가고 클라에서 수정.

**Comment by InHyeok-J** [comment]
> 위의 로그들은 클라에서는 한국시간 기준 14일 20시로 예약하여 요청을 보냈는데(요청은 "Fri, 15 Oct 2021 07:30:00 GMT" 이런식으로 UTC시간으로 감), +9시간이 되어 15일 오전 5시로 저장된 모습입니다.   

이 부분에서 1. 유저가 14일 20시로 선택해도, 라이브러리 혹은 Date 변환시 문제가 생겨서 req.body. reservedAt 에 +9 시간을 해서 서버로 요청을 보냈다는건지, 2. utils함수가 +9시간 해줘서 14일 20시에서 +9시간을 해줬다는건지 헷갈립니다

현재상황 2번에서, 클라이언트가 출력을 할때 한국기준으로 변환하는 로직이 있나요? 서버에서는 date 생성시, UTC로 생성되는 이슈가 있어서 어플리케이션영역에서 +9시간 저장해서 한국시간으로 맞출려고 했습니다.

근데 인서의 이슈에서 추가적인 상황이 왜 -9시간인지 이해가 안되네용

**Comment by Istiopaxx** [comment]
> 이 부분에서 1. 유저가 14일 20시로 선택해도, 라이브러리 혹은 Date 변환시 문제가 생겨서 req.body. reservedAt 에 +9 시간을 해서 서버로 요청을 보냈다는건지, 2. utils함수가 +9시간 해줘서 14일 20시에서 +9시간을 해줬다는건지 헷갈립니다

아 저거는 이전에 저런 문제가 있어서, 해결했습니다. 기존에는 데이터를 KST 기준으로 보냈습니다. 근데 서버에서 그 데이터를 UTC로 변환하지 않고 그대로 받아들여 +9시간을 하여 저렇게 저장된 모습입니다. 해당 문제는 클라에서 요청 바디를 보낼때 UTC로 변환하여 보내는 것으로 Jandy-Seoultech/Jandy_Web_Front#123 에서 이미 해결했습니다. 제가 잘못 작성했으니 저 내용은 삭제할게요..ㅜ

> 현재상황 2번에서, 클라이언트가 출력을 할때 한국기준으로 변환하는 로직이 있나요? 서버에서는 date 생성시, UTC로 생성되는 이슈가 있어서 어플리케이션영역에서 +9시간 저장해서 한국시간으로 맞출려고 했습니다.

한국 기준으로 변환하는 로직은 명시적으로는 없지만 new Date(reservedAt)이 기본적으로 로케일에 맞게 시간을 설정합니다. 즉 서버에서 보내주는 시간이 이미 한국기준 시각이라 하더라도 클라에서 new Date(reservedAt)으로 date 객체를 생성하면 입력으로 받은 reservedAt이 UTC시간으로 인식되고, 생성된 date 객체는 기본적으로 getHours() 같은 함수를 호출할때 한국기준으로 반환해줍니다. 
정리하면 new Date()에 전달하는 인자는 모두 UTC로 인식되고, 반환되는 객체는 로케일을 실행되는 기기(os?)의 타임존으로 설정합니다. 따라서 전달되는 인자는 비록 서버에서 한국시간으로 해줬지만 UTC로 인식되고, getHours()같은 함수들은  한국기준(+9해서)으로 시간을 반환해줍니다.


https://meetup.toast.com/posts/130

**Comment by sjsjsj1246** [comment]
1. 모든 시간을 다 한국으로 맞추고 한국에서만 서비스하거나
2. 모든 시간을 다 UTC로 맞추고 클라이언트에서 toLocaleString으로 사용자 시간대 시간으로 보이게 하거나

1번을 의도하신 것 같으나 서버 로직이
1. 클라에서 시간 받아옴
2. new Date()가 시간을 UTC로 바꿈
3. DB에 +9시간을 해서 더함 (이게 한국 시간)
4. 하지만 클라에 이 +9된 시간을 UTC로 줌
5. 클라는 +9가 된 시간이 UTC시간인것으로 인식하므로 한국에서 toLocaleString을 하면 시간이 한번 더 +9가 됨

따라서 1번으로 가시려면 AWS의 타임존을 바꿔야 합니다.
2번으로 하시려면 +9만 안하면 됩니다.

https://github.com/Jandy-SeoulTech/Jandy_Web_Back/blob/dc3b36b2008606bfb558e08daf52ba8ff1ca3d12/src/utils/dayUtils.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L1-L3

**Comment by InHyeok-J** [comment]
클라이언트가 Local UTC로 변환하는 로직이 있다면 시간을 다 +9로 안바꾸고 UTC 0 으로 저장시키겠습니다 #10 이슈때문에 createdAt도 +9로 해줬는데 이 부분도 삭제하겠습니다. (이슈 설명을 하자면 createdAt에 deafult로 생성되는 time이 UTC만 적용되기에(MySQL에 적용된 TImezone 셋팅 미적용) KST로 적용하기 위해 +9로 DB에 저장을 했음)
이렇게 된다면 +9 시간을 하고 만약 포스트,아카이브 생성 시간 등에도 LocalUTC로 바꾸는 로직이 들어가야 할 것 같네요

---

@KeisLuv5991 AWS가 UTC+0 이라면 스케쥴링이 잘 적용될텐데 이부분은 테스트 해봐야하고
그리고 제가 말한 형태로 바꾼다고 하면 DB 수정이 필수인데 어떻게생각하시나요

생각해봐야 할게
UTC 0기준으로 한다고하면
1. DB 및 레포지토리 코드 수정 코스트 관련
2. 스케쥴링 동작 테스트

이 두 부분을 고려해야합니다

**Comment by Istiopaxx** [comment]
1. AWS ec2는 os 타임존이 기본적으로 UTC(GMT)로 설정됩니다. 즉 UTC+0이 맞습니다.
2. mysql 타임존 설정도 설정 안할시 os 타임존을 따라가는 걸로 알고있는데, 이것도 서버와의 통일성을 위해 UTC+0으로 맞추는게 좋아보입니다.(지금은 UTC+0인것으로 보이므로 따로 변경필요없음)
2. new Date함수는 기본적으로 os 타임존에 맞게 만들어줍니다. 따라서 클라의 코스트가 크진 않습니다.
3. 스케쥴링 동작 테스트는 어차피 +9를 해준 시간이 아니라 UTC 기준으로 잡기 때문에 괜찮아 보입니다.
4. DB 및 레포지토리 코드는 수정할 것 없이 dayUtils 함수에서 `.add(9, "hour")` 부분만 삭제하는게 어떨까요? 나중에 로케일 관련 설정해줄게 있다고 치면 util 함수 자체를 다 없애는 것 보다는 저렇게 전처리 함수가 있는게 좋아보입니다.

**Comment by InHyeok-J** [comment]
굳 그렇게 하죠
