### ISSUE TITLE
Bug: 검색 라우트 응답 객체에 전체 갯수 부재

### ISSUE THREAD

**Issue by Istiopaxx** [Jandy-SeoulTech/Jandy_Web_Back#115]
**버그를 설명해주세요**
GET /api/Search 응답 객체에 전체 검색된 갯수가 없습니다.

**맞는 동작**
응답객체는 전체 검색된 갯수를 포함해야 합니다. 아래는 응답 예시입니다.
```JSON
{
    "total" : 32,
    "data" : [
        {},
        {},
    ]
}
```

**추가적인 상황**
문제를 해결하는데 도움되는 당시의 상황을 적어주세요.

**Comment by iqeq1945** [comment]
@KeisLuv5991  
전체 결과 개수라는 게 지금까지 전부 받아온 Data개수를 말하는 걸까요, 호출하면서 불러오는 Data의 개수를 의미하는 건가요.
후자에 경우에는 바로 수정가능 하고, 전자에 경우에는 예외사항이 많아 조금 걸릴 것 같습니다.

**Comment by Istiopaxx** [comment]
제 로컬에서 수정했으니 작업안하셔도 됩니다.
