### ISSUE TITLE
Refactor: Contribute guide를 위한 script 셋팅

### ISSUE THREAD

**Issue by InHyeok-J** [Jandy-SeoulTech/Jandy_Web_Back#134]
## 리팩토링 문제 사항

- Contribute를 하기 위해 다른 사람이 git clone를 해서 다운받으면 , Prisma에서 .env 파일을 기본으로 읽기 때문에 .env.dev와 .env.prod로동작하는 prisma 관련 스크립트 명령어를 명시해주는것이 좋아보입니다.

### 스크립트 셋팅
- 예를들면 `npm run dev-db:push` , `npm run prod-db:push` 이렇게 명시해서 다른 .env를 사용할 수 있게끔

**Comment by InHyeok-J** [comment]
@KeisLuv5991  @iqeq1945  어때요

**Comment by iqeq1945** [comment]
옹 저는 좋은 거 같아요. 다른 env 접근하는 방법이 필요 할거 같아요

**Comment by Istiopaxx** [comment]
저도 찬성합니다
