### ISSUE TITLE
Bug: Search시 레포지토리 코드와 DB불일치

### ISSUE THREAD

**Issue by InHyeok-J** [Jandy-SeoulTech/Jandy_Web_Back#138]
**버그를 설명해주세요**
명확하고 정확한 버그에 대한 설명을 해주세요.

#132  로 카테고리에 대한 로직 변경후 검색시 리턴 값에 대한 레포지토리 코드 수정이 이루어지지 않음

**Comment by iqeq1945** [comment]
@InHyeok-J 작업아직 안하셨으면 제가 하겠습니다.
