### ISSUE TITLE
prisma unique error

### ISSUE THREAD

**Issue by iqeq1945** [Jandy-SeoulTech/Jandy_Web_Back#22]
@InHyeok-J 
⚠️  There might be data loss when applying the changes:

  • A unique constraint covering the columns `[followerId,followingId]` on the table `follow` will be added. If there are existing duplicate values, this will fail.

√ Do you want to ignore the warning(s)? ... yes
Error: Database error
Error querying the database: Server error: `ERROR HY000 (1553): Cannot drop index 'PRIMARY': needed in a foreign key constraint'
   0: sql_migration_connector::sql_database_step_applier::apply_migration
             at migration-engine\connectors\sql-migration-connector\src\sql_database_step_applier.rs:11
   1: migration_core::api::SchemaPush
             at migration-engine\core\src\api.rs:161

> unique로 설정하여 id 외래키가 없는게 문제인걸로 보입니다. 아무래도 @id 로 id값을 하나 생성해줘야 하거나 unique에서 @@id로 수정해야할 것 같습니다.

**Comment by InHyeok-J** [comment]
- `@id` 문제가 아닌 로컬 DB에 있는 key 값이랑 최신 dev브런치의 unique로 설정한 key값이랑 충돌나서 그런듯.
로컬 DB에 follow 테이블의 외래키 날리고 다시 db push해봐
