### ISSUE TITLE
migration from GCP to AWS With Docker

### ISSUE THREAD

**Issue by InHyeok-J** [Jandy-SeoulTech/Jandy_Web_Back#51]
### Why?
- 무료 구글 클라우드 플랫폼 시작일 8.2, 종료일 11.1
- OSS 대회 2차 평가 기간 10.25~ 11.5,  11.9 (화) 발표 평가
- 무료 기간에 불가능하기 때문에 환경 변경 필요

## 개발 사항
- docker 도입
- aws 환경 구축

### Docker 
- 프로젝트에 도커 셋팅 및 테스팅

### AWS 환경 구축
- EC2
- Docker로 구축
- 구글 클라우드 스토리지 -> AWS 로 multer 변경
- AWS RDBMS를 사용하면 적용,

**Comment by Istiopaxx** [comment]
@InHyeok-J 인혁이형 내일 학교가는데 시간되시면 같이 하시죠. 
ec2 ami 만들고, ec2 -> 서버 인스턴스, rds -> 디비 인스턴스, 도커파일 작성 및 이미지 업로드 및 설정하면 되겠죠?
서버쪽에 혹시 nginx나 로드밸런서 같은거 붙히면 aws 기능을 활용하는것도 생각해보구요.

**Comment by InHyeok-J** [comment]
@KeisLuv5991 내일 저녁 이후로는 안돼서 1~6시에는 가능

**Comment by Istiopaxx** [comment]
네 연락드릴게용 아마 2시쯤 갈거같아요.

**Comment by InHyeok-J** [comment]
오케이 ~
