### ISSUE TITLE
Babel Error

### ISSUE THREAD

**Issue by iqeq1945** [Jandy-SeoulTech/Jandy_Web_Back#57]
## What

Babel 관련 오류 발생, 어디가 문제인지 확인 불가능
> 'babel-node'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는배치 파일이 아닙니다

**Comment by InHyeok-J** [comment]
@babel/cli 혹시 글로벌로 설치해볼래??

**Comment by InHyeok-J** [comment]
아마 npx babel-node 하면 될거같은데
