### ISSUE TITLE
프로필 조회 API 필드 값 이슈

### ISSUE THREAD

**Issue by md2eoseo** [Jandy-SeoulTech/Jandy_Web_Back#59]
프로필 조회 API에 추가해주신 admin, participants 필드를 확인해봤습니다.

API 명세서에 예시로 적어주신 응답은
```json
"admin": [],
"participants": [
  {
    "channel": {
      "id": 1,
      "name": "축.잘.모",
      "introduce": "축구를 잘하든 잘못하든 사람들의 모임입니다.",
      "adminId": 3,
      "createdAt": "2021-09-08T14:51:13.044Z",
      "updatedAt": null,
      "channelImage": {
        "id": 4,
        "src": "...",
        "createdAt": "2021-09-08T14:51:13.044Z",
        "updatedAt": null,
        "profileId": null,
        "channelId": 1,
        "postId": null
      }
    }
  }
]
```
이렇게 나와있습니다. 실제로 응답을 받으면 위처럼 나옵니다.

그런데 admin 필드 값을 받아보면 
```json
"admin": [
  {
    "id": 1,
    "name": "축.잘.모",
    "introduce": "축구를 잘하든 잘못하든 사람들의 모임입니다.",
    "adminId": 3,
    "createdAt": "2021-09-08T14:51:13.044Z",
    "updatedAt": null,
    "channelImage": {
      "id": 4,
      "src": "...",
      "createdAt": "2021-09-08T14:51:13.044Z",
      "updatedAt": null,
      "profileId": null,
      "channelId": 1,
      "postId": null
    }
  }
]
```
이렇게 channel 안에 있지 않은 형태로 받습니다.
저는 admin 필드 값처럼 굳이 channel 프로퍼티 안에 넣지 않고 admin, participants 필드의 형태를 똑같게 수정하는게 좋다고 생각합니다.

**Comment by InHyeok-J** [comment]
- 둘의 데이터 형식이 같아야 하는 이유가 있나요?
- `admin 관계`는 1:다 ` 참여 채널 관계`는 다:다 관계이기에 데이터 형식이 이렇게 나옵니다. 지금은 DB에 쿼리를 한번만 요청해서 관계맺어진 데이터를 한번에 불러오기에 둘이 관계형식이 달라서 응답 값이 다른겁니다.
-  DB에 여러번 쿼리를 요청해서 응답값을 통일 시킬 수는 있으나 성능적으로 더 안좋아지는 상황입니다.(정확히 말하며는 어느 부분이 성능이 최적화되는지는 잘 모르겠습니다만 DB 접근 한번 하는게 더 좋다고 판단했습니다)
- 위에서 설명한대로 둘 사이의 관계가 다르기 때문에 리턴값이 다르며
```
 participants:[
   channel:{
       ...data
   },
   channel:{
       ...data
   },
   ...
]
```
이렇게 동일한 형식으로 데이터가 리턴되기에 실제 프론트에서 데이터를 렌더링하는데는 크게 문제가 없다고 생각이 듭니다.
- 서버에서 순수 js 코드로 비구조화할당 등 데이터를 다시 재가공 해서 보내줄 수는 있으나 이러면 로직과는 관계없는 코드가 수십줄이 생길 것 같습니다. 혹시 저 데이터 형식으로 인해 프론트에서 성능적인 이슈가 발생하면 댓 달아주세요

**Comment by md2eoseo** [comment]
프론트에서의 성능적인 이슈 때문에 수정이 필요하다기보다는 API 응답 값이 같은 데이터 모델을 보여주는데 값의 형태가 다르다보니 통일성이 깨지는 것 같아 이슈로 올렸습니다. 저만 그랬을 수도 있지만 제가 명세서를 봤을 때는 admin도 participants와 같이 channel 프로퍼티 안에 채널 데이터가 있을거라고 판단했습니다. 실제로 확인해보니 다른 구조였고, 만약 그게 같은 데이터 모델을 나타내면서 다른 구조로 보여준다면 API 명세서의 예시 응답 값에 써주는게 좋을 것 같습니다.
그리고 백엔드에서 participants의 경우에는
```participants.map(channel => channel.channel)```을 ```participants```에 할당시켜주면 ```admin```처럼 데이터 형태를 만들 수 있을 것 같습니다.

**Comment by sjsjsj1246** [comment]
앞으로 작성하는 API는
다대다 구조일 경우 비구조화 할당을 통해 값을 빼낼 수 있을 것 같습니다만
기존에 있는 코드를 리펙토링 하는 것은 그것 자체로도 시간이 많이 소요되고 프론트에서도 전부 수정해줘야 하기 때문에 비용이 클 것 같습니다.

**Comment by InHyeok-J** [comment]
음 이문제를 인지하고 있긴 했는데 js 영역에서 해결하는것이 아닌 ORM 영역에서 해결하고 싶어서 현재 상태를 두긴했습니다.
실제로 제가 직접 스택오버플로우 [링크](https://stackoverflow.com/questions/69319651/how-to-reduce-prisma-selector-include-field-code-line)에 질문하기도 했는데 아직 답이 안달렸네요.
일단 현재 해야하는 작업(docker)가 있기에 위에 인서가 말한대로 추후 작업을 해야 할것 같습니다.

**Comment by md2eoseo** [comment]
네 프론트에서 처리하는건 크게 문제 없으니 그대로 진행하겠습니다~

**Comment by InHyeok-J** [comment]
추후 작업에서 관계형 데이터일때 고려해서 짜겠습니다
