### ISSUE TITLE
포스트 아카이빙 기능 구현

### ISSUE THREAD

**Issue by InHyeok-J** [Jandy-SeoulTech/Jandy_Web_Back#64]
## 포스트 아키이빙 기능 구현 (Feature1)
- 9.29 회의에서 정한 사항입니다.
- 포스트랑 아카이빙이 완벽히 분리되는 개념이 아닙니다.
- 포스트 아카이빙에는 공개 범위가 있습니다.
    - public -> 전체 공개, 유저의 프로필의 모아보기에 보여줄 수 있음.
    - private ->  채널 유저만 공개, 유저 프로필에는 보이지 않고, 채널 모아보기에만 보임
- 포스트 아카이빙에도 좋아요가 있습니다.
- 댓글도 있음

## 1. 포스트 아카이빙 생성
- 포스트 아카이빙 글을 작성할 때, 로그인한 유저의 종료된 채팅방이 있으면(로그인한 유저가 방장인 경우) 요청 유저의 채팅방 목록 및 게시글 정보를 줌
- 로그인한 유저의 종료된 채팅방이 있는 경우 체크는 프론트가 해야 할 것 같습니다 @sjsjsj1246 
- entry point는 하나이며 유저의 종료된 채팅방이 있는경우만 프론트가 체크해줌.

### 1.1 종료된 채팅방이 있는 경우 (아카이빙)
- 종료된 채팅방이 있는 경우, 글 작성자가 채팅방 리스트 목록을 불러오겠다고 하면 `로그인 한 유저의 채팅방 리스트 를 불러오는 API` 를 통해 리스트를 줍니다. 이후 리스트를 선택 하면 그 `방의 답장 쌍 리스트 불러오기 API` 를 통해 답장을 프론트가 렌더링 해줍니다. 
- 이후 게시판 재능 공유와 같은 로직으로 글 작성.
- 채팅방 리스트 정보에는 채팅방이 생성한 글 데이터까지 포함되어야 합니다.
    - 프론트가 나중에 렌더링을 해줍니다.  포스트 스크랩 처럼

### 1.2 종료된 채팅방이 없는 경우 (포스트)
-  게시판 재능 공유와 같은 로직으로 글 작성.

### 추가
-  실제 데이터는 html 데이터로 담겨서 서버로 전송될듯합니다

 ## 포스트 아카이빙으로 인한 변경사항 (Feature2)

### 1. 프로필 페이지 모아보기
- 프로필페이지에는 그 유저가 작성한 아카이빙의 public만 보여줍니다.
- **`이번 이슈에서 여기까지 수정 바랍니다`**

### 2. 재능 공유 게시판의 상태 추가
- 재능 공유 게시판에 기존에는 공지. 채팅방 예약, 채팅방 열림, 안열림 이렇게 4개의 상태가 있었는데 
- 공지, 채팅방 예약,오픈, 채팅 대기(안열림), 해결완료 이렇게 변경되며 이거는 다른 이슈에 추가적으로 작성하겠습니다

### 요약
- 포스트아카이빙 생성 API
- 로그인한 유저가 채팅방 주인인 채팅방 리스트 API
- 채팅방의 질문답장쌍 API
- 포스트 아카이빙 전체 조회 API
- 포스트 아카이빙 개별 조회 API
- 프로필 페이지 모아보기 API(public)
- 포스팅 아카이빙 좋아요,취소 API
- 포스팅 아카이빙 댓글 API

**Comment by InHyeok-J** [comment]
@KeisLuv5991  저번 회의 바탕으로 적었는데 혹시 더 추가되야할것 있으면 알려줘

**Comment by InHyeok-J** [comment]
어 포스트 아카이빙 네이밍 뭘로하기로 했지 기억이 잘안나는데 blog 였나 writing ? archive? 애매하면 아카이브로 함..

**Comment by Istiopaxx** [comment]
https://docs.google.com/document/d/1NQ_QssmziW127APOte1fqzlU2RQ52e6I8NlaMY0ee9o/edit
기능 명세서에 제가 생각한 데이터 구조 작성해놧습니다. 개발하다가 이거 필요할거 같은데? 시 자율적인 추가
### 포스팅/아카이빙 구조
1. 작성자
2. 제목
2. 작성(수정)시간 - 일시분
3. 게시시간 - 일시분
4. 아카이빙 여부? -> true면 질문-답장쌍 목록이 있음
5. 소속된 채널
6. 공개 범위
    - private 공개
        + 채널 참여자(+작성자)만 볼 수 있음
    - 전체 공개
        + 채널 프로필 모아보기 목록에 노출됨
        + 작성자 프로필 모아보기 목록에 노출됨
        + 검색엔진에 노출됨
    - 공개 범위는 아카이빙/포스팅 작성자가 작성할 때 결정합니다. 기본값은 전체 공개
    - 전체 공개인 경우 찾아보기 탭(탐색기능)에서 노출
7. 본문
    - 아카이빙의 경우
       + 선택된 질문-답장 쌍 목록 포함
    - 텍스트 - md 형식의 스트링
8. 댓글 목록
   - 댓글 구조
       + 작성자
       + 작성(수정)시간
       + 본문(텍스트)
   - 댓글 권한
       + 댓글 작성자 - 수정, 삭제
       + 그외 - 신고
    - 채널 게시글 댓글 기능과 똑같습니다.

### API 목록
 형이 적어주신 API 목록대로면 충분할 것 같아요.

### 포스트/아카이빙 네이밍 
 archive로 하시죠~~

**Comment by sjsjsj1246** [comment]
둘다 네이밍이 아카이브인가요?

**Comment by Istiopaxx** [comment]
채널에 재능공유요청은  post, 채널에 종속되지 않은 포스트/아카이빙(즉 둘다?)은 archive로 하려고 생각중입니다~~

**Comment by sjsjsj1246** [comment]
@md2eoseo 성태님~ 포스트/아카이빙은 둘다 하나의 아카이빙이라는 네이밍을 사용하겠습니다. (Archiving)
그냥 글만 쓰는것도 아카이빙, 채팅방에서 아카이빙을 할 경우 글 + 채팅내용인 구조로 개발하죠

**Comment by InHyeok-J** [comment]
아주 나이쓰

**Comment by md2eoseo** [comment]
@InHyeok-J 명세서에 나와 있는 `/api/Post` 사용하면 지금 개발중인 아카이빙 글 작성할 수 있나요?

**Comment by InHyeok-J** [comment]
@md2eoseo  아뇨 이번주 개발사항이고 다음주부터가능합니다

**Comment by Istiopaxx** [comment]
@InHyeok-J @iqeq1945 각 API에 대해 이슈 작성했습니다. 혹시 작업중인 이슈있으면 셀프 어사인해주시고, 내일 어사인안된거 제가 개발할게요. #67 에서 archive 테이블 생성 및 기타 서비스 파일, 컨트롤러 파일, 레포지토리 파일, 라우트 정의 등등 기본 작업을 하고 #68 #69 #70 순으로 이어 개발하면 되겠습니다. 
Archive 기능에 대해 모두 개발되면 이 이슈는 닫을게요. PR 링킹은 각 서브태스크별로 만든 이슈에 링킹해주시고, 이 이슈는 PR에 링크하지 말아주세요~!
