### ISSUE TITLE
채널 공유 요청 게시글리스트 조회 리팩토링 

### ISSUE THREAD

**Issue by InHyeok-J** [Jandy-SeoulTech/Jandy_Web_Back#65]
## 채널 공유 게시판 글 조회 기능 수정
- 기존에는 공지/ 채팅방 열림/ 예약/ 안열림 순으로  줬습
- 게시글리스트 조회 방식을 변경함
- 디폴트 : (선택x) : 공지 / 그외 시간 순서
- (채팅방선택??) 채팅방예약,오픈된 공유 요청 게시글
- 채팅 대기 -> 기존 안열림, 채팅방 예약이나 공유 요청이 안된 게시글만 조회
- 해결완료 -> 채팅방이 종료되고, 아카이빙이 있는 게시글 조회

### 채팅방이 종료된 게시글 1개 조회 수정
- 포스트 아카이빙이 생긴 데이터는 게시글을 조회할때 스크랩처럼 렌더링을 해줘야 하기 때문에 아카이빙 정보도 리턴해줘야함

**Comment by Istiopaxx** [comment]
추가로, 아카이브 등록 시 연결된 포스트를 해결완료(archived) 상태로 업데이트하는 로직도 추가하겠습니다.

**Comment by Istiopaxx** [comment]
https://github.com/Jandy-SeoulTech/Jandy_Web_Back/pull/87#issuecomment-939410832
GET /api/Post/channel/:channelId 에서 응답으로 주는 JSON 객체에 totalPage도 포함하도록 하겠습니다.
