### ISSUE TITLE
Archive 생성 API

### ISSUE THREAD

**Issue by Istiopaxx** [Jandy-SeoulTech/Jandy_Web_Back#67]
## 개발사항
1. 아카이브 생성 API를 작성합니다.
2. 디비에 아카이브 테이블을 생성합니다.
3. 필요한 repository 함수를 정의합니다.
4. 서비스와 컨트롤러를 정의합니다.
5.

**Comment by Istiopaxx** [comment]
이거 작업상황이 어떻게 되가나요~~~??

**Comment by iqeq1945** [comment]
> 이거 작업상황이 어떻게 되가나요~~~??

지금거의 다 작성해서 올릴예정입니다.

**Comment by Istiopaxx** [comment]
오케이 알겠습니다~~ PR올라오면 바로 리뷰후 추가 개발할게요
