### ISSUE TITLE
Archive table 구조에 대한 논의

### ISSUE THREAD

**Issue by iqeq1945** [Jandy-SeoulTech/Jandy_Web_Back#72]
## 아카이빙 table 구조 논의

> 추후 Table의 변경을 줄이기 위해 issue을 열었습니다. 

- 현재 제작한 테이블 구조

```javascript
model Archive {
  id                  Int @id @default(autoincrement())
  status              ArchiveStatus // Private, Public 공개범위
  content             String // 아카이빙에 들어갈 (게시글, 질문답쌍)에 대한 추가 내용 혹은 포스팅
  archiveComment      Comment[] // 아카이빙에 속하는 댓글 목록
  owner               User @relation("archive", fields: [ownerId], references: [id]) 
  ownerId             Int // 아카이빙의 소유주 
  channel             Channel @relation(fields: [channelId], references: [id])
  channelId           Int // 공개범위가 Private시 속한 채널의 유저를 판별하기위한 값
  post                Post? @relation(fields: [postId], references: [id])
  postId              Int // 주제가 되는 POST 정보
  chatMessage         ChatMessage[] // 질문답쌍의 정보
  createdAt           DateTime
  updatedAt           DateTime?
  @@map("archives")
}

enum ArchiveStatus {
  Private
  Public
}
```

### channel
- one to many 관계
- channel 정보의 경우, 아카이빙은 채널에서 작성이 되기 때문에 필수. (공유요청 상관x), 공개 범위가 private인 경우, 판별을 위해 사용되기도 함.

```
model Channel {
...
  archive      Archive[]
...
}
```

### chatMessage
- archive : one to many 관계
- 재능 공유 요청에 대해  종료된 채팅방을 통해 만들어진 경우, 채팅방의 대화 내역(chatMessage 중 답장글과 답장을 단 질문글의 정보만가져옴)정보를 가져옴

```
model ChatMessage {
...
  archive         Archive?  @relation(fields: [archiveId], references: [id])
  archiveId       Int? // 질문 답쌍을 전달하기 위한 아카이브
...
}
```

### post
- archive : one to one 관계
- 어떤 post에서 시작했는지 알기위해 채팅방에서 post의 정보를 가져옴
```
model Post {
...
  archive         Archive?
...
}
```

### content
- 공유 요청에 대한 글인 경우, post와 chatMessage 내용의 보충 설명 작성 
- 공유 요청에 대한 글이 아닌 경우, post와 비슷한 형식

### comment

- Archive나 Post의 댓글은 동일하여 같은 table을 사용
```
model Comment {
....
  post      Post?      @relation(fields: [postId], references: [id])
  postId    Int
  archive   Archive? @relation(fields: [archiveId], references: [id])
  archiveId Int
...
}
```

**Comment by iqeq1945** [comment]
현재 흐름이 공유 요청이 없으면, 단순히 post의 기능과 동일하고 channel의 정보만  문제가 없어 보입니다.

공유 요청의 경우, 선택한 채팅방(ChannelRoom)에서 post, channel, rooomOwner, chatMessage 내용을 얻을 수 있다고 생각하여, Archive table에는 채팅방 자체의 정보는 넣지 않았습니다.

이상한 점있으면 의견주시면 감사하겠습니다.

**Comment by InHyeok-J** [comment]
일단 아카이브의 제목?이 기획상에 없는지, 아니면 고려안하신지 궁금합니다.
또한 chatMessage는 없어도 될 것 같네요 1. 실제 db에 저장하는건 content안에 값이 저장되기 때문이고, 아카이빙이 생성되면 2.채팅방도 삭제되며, 그에따른 챗 메시지도 없어집니다 . 
만약 1번이 아니라고 하면 2번때문에 로직 논의를 다시 해봐야합니다.

**Comment by Istiopaxx** [comment]
아카이브의 제목은 두가지 방법으로 데이터를 정의할 수 있을것 같습니다.
1. Archive 객체의 프로퍼티로 넣기(즉 루트에 넣습니다.)
```
model Archive {
  ...
  title     String
  content   String
  ...
}
```
2. Archive 객체의 content 프로퍼티에 객체를 넣고, 해당 객체에 넣기
```
content : {
    title: "제목",
    body: "## 본문입니다.",
}
```
제 생각엔 전체적인 통일성을 위해 1번으로 가는 것이 좋겠네요. Post 테이블은 확인해보니 타이틀이 1번처럼 되어있어용

**Comment by InHyeok-J** [comment]
@KeisLuv5991 1번안 동의합니다.

**Comment by Istiopaxx** [comment]
> 일단 아카이브의 제목?이 기획상에 없는지, 아니면 고려안하신지 궁금합니다. 또한 chatMessage는 없어도 될 것 같네요 1. 실제 db에 저장하는건 content안에 값이 저장되기 때문이고, 아카이빙이 생성되면 2.채팅방도 삭제되며, 그에따른 챗 메시지도 없어집니다 . 만약 1번이 아니라고 하면 2번때문에 로직 논의를 다시 해봐야합니다.

이부분은 와프가 나오면 확실하게 말씀드릴수 있는부분인데, 저랑 연수님은 디자인 회의할때 본문 영역과 채팅내역 영역을 분리하는 걸로 얘기했었어요. 채팅 내역(즉 질문/답장쌍) 은 좀 더 컴포넌트화시켜서 더 디자인을 입히는 쪽으로 생각했는데, 만약 content(string 타입) 안에 질문-답장쌍이 포함되어 있으면 질문-답장쌍을 파싱해서 따로 빼내는 클라이언트의 추가 작업이 있어야 합니다. 
제 의견은 클라에서의 파싱작업을 피할 수 있게  chatmessage(질문-답장 쌍의 목록) 프로퍼티가 archive 테이블에 있어야 한다고 생각합니다.

**Comment by InHyeok-J** [comment]
@KeisLuv5991  더 디자인을 입힌다는게 아카이빙을 생성하고 커스텀 할 수 있게 하는건가?? 생성 전에 메시지 목록을 보내서 프론트가 상태관리하면서 값을 관리를해준다면 상관없을거같은데.. 오늘 회의때 논의함해봅시다

**Comment by iqeq1945** [comment]
공유 요청에 경우, 제목이 바뀌는 경우가 있는지 논의사항인 것 같아 빼놓았었는데, 논의 주제로 올리는 걸 잊었네요. 저도 1번안이 좋은 것 같아 제목에 관해서는 1번안을 채택하여 진행하겠습니다.
