### ISSUE TITLE
/api/Channel/info/:channelId 버그

### ISSUE THREAD

**Issue by sjsjsj1246** [Jandy-SeoulTech/Jandy_Web_Back#83]
채널 정보를 가져오는 API가 항상 403 에러가 납니다. 아마 기존의 채널프로필 이미지와의 관계 문제 때문이지 않을까 싶습니다.
![image](https://user-images.githubusercontent.com/24623403/136602826-5b57cc86-cd79-4487-818d-d5fc07a0f602.png)

추가적으로 이슈에 라벨을 달수가 없는데 권한좀 주시겠어요?

**Comment by InHyeok-J** [comment]
채널 프로필이미지 변경하면서 생긴 이슈 맞는거같넹 이거 오늘 이미지 db 업데이트 하면서 바로 바꿀게

**Comment by InHyeok-J** [comment]
@KeisLuv5991  이미지 DB 변경후 배포 한적 있어? Dockerfile 대로 다시 빌드했다면 이런 이슈가 없을텐데 db channel
<img width="932" alt="스크린샷 2021-10-09 오전 4 54 57" src="https://user-images.githubusercontent.com/28949213/136617892-56a0e41a-1544-43e6-bbd6-5a3438026972.png">
에 컬럼 추가가 안된거 보면 db push가 안먹었고, 그러면 Dockerfile로 했는데도 이슈가 생긴건가?   



---
지금 제배포하니깐 pul 받아오는거 보니 다시 배포한적 없는데 문제가 생긴거였네 이거는 왜 문제가생겼는지 확인해봐야할듯

**Comment by Istiopaxx** [comment]
https://github.com/Jandy-SeoulTech/Jandy_Web_Back/blob/f428fba2bb70ab85ecfdbd0350cfa00b1b6628f2/prisma/schema.prisma#L122-L145
https://github.com/Jandy-SeoulTech/Jandy_Web_Back/blob/f428fba2bb70ab85ecfdbd0350cfa00b1b6628f2/src/repositories/ChannelRepository.js#L79-L83

channellike로 되어있어서 오류나는 중입니다
